### ISSUE TITLE
Introduction of template generator in JS

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#103]
@MarekBleschke @cmwd we need to choose and implement some kind of template generator in JS.

Any suggestions are welcome.

**Comment by MarekBleschke** [comment]
IMO http://handlebarsjs.com/ is pretty good.

**Comment by magul** [comment]
There were bug for that: #70 .

From that bug:

```
We should choose one from:

http://underscorejs.org/
https://mustache.github.io/
http://handlebarsjs.com/
```

We are already using underscore. @MarekBleschke are You think, that handlebars has so much pros to migrate to it?

**Comment by magul** [comment]
I spoke with @cmwd on FB and ha had some doubts if we need such huge template engine, but we will go right now with patter "design first, optimize later" and we will introduce handlebars.
