### ISSUE TITLE
Przeciągnięcie przedmiotu

### ISSUE THREAD

**Issue by gogracek** [komitywa/plantingjs#114]
JAKO Uczestnik
CHCĘ przeciągnąć przedmiot w wybrane przez siebie miejsce
ŻEBY go tam wstawić

**Comment by magul** [comment]
To już jest zrobione. Mamy buga, ponieważ jak się umieszcza na początku obiekt, to on się pojawia na pewnej wysokości, niezależnie od tego, gdzie obiekt zostanie umieszczony, ale później daje się go przeciągać.

Błąd będziemy rozwiązywać jako buga.
