### ISSUE TITLE
Usunięcie przedmiotu z widoku ulicy

### ISSUE THREAD

**Issue by gogracek** [komitywa/plantingjs#115]
JAKO Uczestnik
CHCĘ po upuszczeniu przedmiotu, ale jeszcze na hoverze, w prawym górnym rogu zobaczyć "x"
ŻEBY kliknąć w niego i usunąć go z widoku ulicy.

**Comment by magul** [comment]
X istnieje i daje się usunąć obiekt. Zrobione.
