### ISSUE TITLE
Ikony do katalogu

### ISSUE THREAD

**Issue by gogracek** [komitywa/plantingjs#125]
JAKO inicjator (lub uczestnik)
CHCĘ zobaczyć przedmioty, których mogę użyć
ŻEBY je dodać do panelu kampanii (lub jako uczestnik wstawić w swoim planting)

**Comment by gogracek** [comment]
Hania, potrzebuję pociętych ikon, które wstawimy do katalogu i które inicjator udostępni uczestnikom w swojej kampanii. Na razie w jednym rozmiarze (katalog jeszcze nie będzie działał).

**Comment by magul** [comment]
@hankozaur mamy 2 taski na ten tydzień zablokowane, więc będziemy wdzięczni, jeżeli ten temat ruszy dosyć priorytetowo.

**Comment by hankozaur** [comment]
ikonki w pngach od dluzszego czasu leżą tu:
https://drive.google.com/open?id=0B519SW95w8EURkhHRVpwZ1EzRkk

Jutro wrzucę tam svg - bo coś mi się illustrator w domu tnie!
proszę też o pisanie o formatach // wielkościach w zadaniu :)

**Comment by magul** [comment]
Done - icons are available here: https://drive.google.com/folderview?id=0B519SW95w8EUNEVGdFVnaG9qeU0&usp=drive_web&tid=0B519SW95w8EURkhHRVpwZ1EzRkk
