### ISSUE TITLE
Usuń skalowanie

### ISSUE THREAD

**Issue by gogracek** [komitywa/plantingjs#128]
Rezygnuję z powiększania i pomniejszania obiektów w pierwszej wersji. Może będzie potrzebne w kolejnych.

**Comment by cmwd** [comment]
@twain83

**Comment by magul** [comment]
@cmwd do we decided if we are going to burried whole functionality or are we going to create some kind of switch to enable/disable this functionality?

I don't know. I'm willing to leave this call for You to decide.

**Comment by gogracek** [comment]
Just disable it. We might need to rotate object in future, just don't need it now in this version.

**Comment by magul** [comment]
Done in #199
