### ISSUE TITLE
Eslint configuration

### ISSUE THREAD

**Issue by cmwd** [komitywa/plantingjs#133]
I would like to open discussion about eslint configuration. I think some rules are redundant. Sometimes even annoying like [comma-dangle](http://eslint.org/docs/rules/comma-dangle.html). Other useful are missing - [max-len](http://eslint.org/docs/rules/max-len.html) for example.

Also I'm confused by `prefer-const` rule. Consider this block of code:

``` javascript
let classes = [`${blockName}`];

if (modifier) {
  classes.push(`${blockName}-${modifier}`);
}

this.className = classes.join(' ');
```

Eslint yells at me that i should use `const` instead of `let` because variable is never modified. Well thats not exactly true because of conditional push. Maybe We should report it as a bug to eslint team?

Is worth to say that we dont need to change everything to append some changes. Our config inherits from airbnb settings and we can easily override some rules.

**Comment by cmwd** [comment]
Update: `prefer-const` works fine... const mean constant variable not constant value. So its my bad :)

**Comment by cmwd** [comment]
``` javascript
max-len: [1, 80],
comma-dangle: [1]
```

**Comment by magul** [comment]
@rudymichal

**Comment by rudymichal** [comment]
done in #175

**Comment by cmwd** [comment]
@rudymichal could you also adjust `guard-for-in` ?

**Comment by cmwd** [comment]
Done in d398d8ef91e34b4d415a5006ca122d0e2a880547
