### ISSUE TITLE
Obsługa warstwowania elementów > #45

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#14]
powiązane z #45  
np. na kliknięcie element wysuwa się do przodu i jest wybrany do edycji

**Comment by mjaniszew** [comment]
Potrzeba jest tutaj lista dodanych warstw/obiektów, aby móc zaznaczyć element znajdujący się pod innym elementem.

**Comment by Yog** [comment]
zrobiłem listę
pr: https://github.com/komitywa/plantingjs/pull/34
jest surowa, ale istnieje w lewym górnym rogu ;)

**Comment by magul** [comment]
Do przejrzenia zmiana Piotra plus dalsze rozbicie na bugi i dowiezienie funkcjonalności.

**Comment by magul** [comment]
@malepoludnie @cmwd Tutaj do zrobienia jest przekazywanie warsty w JSON-ie otrzymanym w planted.

**Comment by gogracek** [comment]
Warstwowanie nie jest potrzebne w pierwszej wersji, usuwam.
