### ISSUE TITLE
Add validation on finish planting

### ISSUE THREAD

**Issue by cmwd** [komitywa/plantingjs#177]
Right now engine allows to finish planting even when we didn't plant any object. I'm not sure that we should validate it on engine or on server side (or both?). We could add some warning or disable save button if user didn't choose any object.

**Comment by magul** [comment]
@malepoludnie ?

**Comment by gogracek** [comment]
You're right, save should be disabled unless you plant sth.

**Comment by magul** [comment]
@rudymichal

**Comment by magul** [comment]
Done in #183
