### ISSUE TITLE
We need to rethink the place of wybierz button

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#188]
Right now it is overlapping on `+` and `-` of Google Maps zoom.
![zrzut ekranu z 2016-03-25 20-31-39](https://cloud.githubusercontent.com/assets/1165138/14052212/c1947762-f2c8-11e5-8ce0-cf97be17cee0.png)

**Comment by gogracek** [comment]
Przekazałem Hance razem ze szkicami flow dla zakładającego kampanię.
