### ISSUE TITLE
We need to check if We actaully are using _fonts.scss

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#195]

**Comment by magul** [comment]
As far as I checked we are using this `_fonts.sccs` for serving font-based icons. There are few situation we use them, in few situation it looks that code is not used anymore.

Fonts have been generated somehow at site https://icomoon.io/ and introduced into code in commit https://github.com/komitywa/plantingjs/commit/9f6495d0. We need to find out how the are licenced and what to do if we will need to remove them from repository.

**Comment by magul** [comment]
@Yog is this possible to determine how licenced are these icons?

**Comment by magul** [comment]
I have also checked what icons in fact we use and right now we use:
- icon-trash
- icon-resize
- icon-loop
- icon-menu-hamburger

**Comment by Yog** [comment]
right now, as i look through their shapes it appears thei might be part of 
http://getbootstrap.com/components/#glyphicons
or 
https://icomoon.io/#preview-free
The icon-trash is likely a custom one

If you'd like, you can add licences from these two above. 
But if you look through internet through all icons available, you will find duplicates and similiar icons, which would imply that one is derivation of the other or they were made independently by accident.
