### ISSUE TITLE
Dziwne artefakty w trybie wysadzania [OSX - Chrome]

### ISSUE THREAD

**Issue by mjaniszew** [komitywa/plantingjs#20]
Na chromie w OSX widok google street view może się krzaczyć kiedy odpali się wysadzanie.

W PÓŹNIEJSZYM ETAPIE LEPIEJ TO SPRAWDZIĆ.

**Comment by cmwd** [comment]
Mamy ścieżkę błędu ? Sprawdzałem na Chrome / Canary nie trafiłem na podobny problem.
