### ISSUE TITLE
Lewy górny róg - co to?

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#37]
![lewy_gorny_rog](https://cloud.githubusercontent.com/assets/1165138/9142124/f9f39106-3d3d-11e5-853e-89d36d4f0000.png)

Ustalić skąd to się tu wzięło i jeżeli nie ma większego sensu, to usunąć

**Comment by Yog** [comment]
to się bierze ze zgłoszenia https://github.com/komitywa/plantingjs/issues/14

**Comment by Yezior** [comment]
będziemy to rozwijać i dodawać strzałki góra/dół do zarządzania warstwami

**Comment by magul** [comment]
To był początek silnika warstowania. Już jest zrobione. Zamykam.
