### ISSUE TITLE
Prowizaryczne zwijanie toolboxa

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#39]
![toolbox](https://cloud.githubusercontent.com/assets/1165138/9143138/d201cce2-3d44-11e5-9046-c4405c3a5435.png)

Toolbox ma się zwijać w prawo, jeżeli myszka się nad nim nie znajduje przez odpowiednią ilość czasu.

Ma być dostępna strzałka w lewo rozwijająca tooltip.

**Comment by emilekm** [comment]
I'm on it

**Comment by magul** [comment]
done
