### ISSUE TITLE
Biblioteka dostępna jako pakiet Bowera

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#40]
Należy przystosować bibliotekę do automatycznego budowania pakietu Bowera. Docelowo może to się wykonywać (być sprawdzane) przez Travis CI.

Bower to popularny manager pakietów JavaScript. Dzięki temu rozwiązaniu, programiści, którzy będą chcieli skorzystać z naszej biblioteki będą mogli ściągnąć ją za pomocą jednego polecenia:

```
bower install plantingjs
```

Więcej informacji można znaleźć na http://bower.io/

**Comment by cmwd** [comment]
@magul to zadanie chyba można zamknąć?
