### ISSUE TITLE
Zbudowanie interfejsu do zarządzania warstwami > #14

### ISSUE THREAD

**Issue by cmwd** [komitywa/plantingjs#45]
Powiązane z #14. 
Lista belek odpowiadająca elementom, które aktualnie są wyświetlone. Każda z belek powinna mieć strzałki góra/dół do zmiany kolejności warstw.

(Warstwy są niezbędne, pozwalają symulować głębię)

**Comment by Yog** [comment]
![image](https://cloud.githubusercontent.com/assets/432220/9150675/60b81300-3de6-11e5-93c9-2146856728ef.png)
lista belek w lewym gornym rogu
- Najwyżej są obiekty najbardziej na wierzchu
- obiekt na żółto jest aktywny. Chodzi o to aby wynieść go tymczasowo na wierzch aby dało się klikać jego interfejs i zmienić mu np rozmiar
- elementy na liście warstwowania mają strzałki do zmiany ich pozycji... Ale tak na prawdę lepszy byłby drag&drop bo wtedy dużo łatwiej przenieść obiekt na wierzch o pare pozycji.
  drag&drop jest też trochę bardziej intuicyjny. 
  Można też zastosować oba typy interfejsu na raz, chociaż strzałki zajmuja miejsce
  - dolna i gorna strzałki są wyszarzone,bo ich klikniecie nie przyniesie skutku, bo biekt jest na samym dole/górze

**Comment by Yog** [comment]
bardziej zaawansowana koncepcja z planami
![image](https://cloud.githubusercontent.com/assets/432220/9150684/b84e3698-3de7-11e5-8ad5-3f87ba3a85e0.png)
- chodzi o to aby grupowac obiekty na tym samym planie. 
  - przenoszenie obiektu z innego planu do danego planu może powodować jego automatyczne przeskalowanie do rozmiaru odpowiadającemu wspólczynnikowi powiększenia innych obiektów w tym planie
  - było by to ułatwienie bo uzytkownik sam mógl by sobie ustawić ilość planów, które reprezentowały by rzedy ikon do warstwowania w lewym gornym rogu.
    Plany pozwalają łatwiej okiełznać perspektywę i sprawić, że plan wygląda bardziej składnie

**Comment by magul** [comment]
@malepoludnie Zamykam.

Interfejs mamy, pewnie nie działa tak jak powinien, ale na to zrobimy nowe issue.
