### ISSUE TITLE
interfejs nie skaluje sie razem z obiektem

### ISSUE THREAD

**Issue by Yog** [komitywa/plantingjs#46]
![image](https://cloud.githubusercontent.com/assets/432220/9150561/9a42b654-3ddf-11e5-9b1b-d31b75c32a49.png)
czarne kółko z ikonkami powinno się skalować razem z obrazkiem obiektu
Aktualnie sie tak nie dzieje, bo obrzek img dostaje styl `scale:` gdyby kontrolowany był `width` i `height` to wtedy kontener obrazka tez by sie rozszerzal, a w konsekwencji czarne kółko z interfejsem też.
Aby obiekt pozotawał na środku, trzeba by dawać margines górny i lewy ujemny równy połowie różnicy między nowym height/width a inicjalnym. Chociaż mniej bałaganiarskie było by odejmowanie tego marginesu od styli `top:` i `left:` wypozycjonowanego absolutnie kontenera z całością

**Comment by magul** [comment]
to jeszcze będzie do oceny, jak to ma działać.
