### ISSUE TITLE
Klucz Google Maps API przekazywany w konstruktorze

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#51]
Obecnie podpięty na stałe jeden klucz.

**Comment by cmwd** [comment]
Zrobione w cb4a318c63de4e87e0e35820fd7a41da100cd7c0, [przykład](https://github.com/komitywa/plantingjs/commit/cb4a318c63de4e87e0e35820fd7a41da100cd7c0#diff-716f933924045ede773e81a677c12427R99)
