### ISSUE TITLE
nieintuicyjna rotacja

### ISSUE THREAD

**Issue by hankozaur** [komitywa/plantingjs#56]
Nie działa ikona rotacji obiektu (na chrome)

**Comment by magul** [comment]
Na jakim środowisku? http://plantingjs.org ?

**Comment by magul** [comment]
Czy Ty próbujesz klikać w strzałki? Jeżeli tak, to tak to nie działa i nie jest to bug. Należy kilknąć w kółko pomiędzy strzałkami i przegiągnąć w lewo lub prawo.

**Comment by hankozaur** [comment]
jak klikam w cokolwiek z tych tzrech elelemntow- żaden nie działa :)

2015-09-04 14:47 GMT+02:00 Tomasz Magulski notifications@github.com:

**Comment by magul** [comment]
No dobra, ale będziemy chcieli to zobaczyć na hacknightcie.

**Comment by ron-welty** [comment]
UX do poprawy. Co zrobić, żeby obracanie było intuicyjne?

**Comment by gogracek** [comment]
Wycofaliśmy obracanie, zamykam to zadanie.
