### ISSUE TITLE
Skalowanie

### ISSUE THREAD

**Issue by hankozaur** [komitywa/plantingjs#57]
Skalowanie robi się od lewego górnego rogu. 
Wydaje mi się że powinno skalować się od środka obiektu (na czerwono jak jest // na niebiesko jak obiekt powinien rosnąć)

![bug](https://cloud.githubusercontent.com/assets/11767153/9683774/757d8f8a-5313-11e5-9534-0d3ba1bb7fe6.JPG)

**Comment by magul** [comment]
To akurat nie jest bug (ale dobrze, że to zgłaszasz). Póki co robiliśmy skalowanie, żeby działało. Trzeba będzie się zastanowić, jak ono ma działać, ale mi też intuicja mówi, że tak jak jest to nie powinno być.

**Comment by ron-welty** [comment]
UX do poprawy. Co zrobić, żeby skalowanie było intuicyjne?

**Comment by gogracek** [comment]
Na razie nie będzie skalowania, zamykam temat,
