### ISSUE TITLE
Describe planted JSON structure

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#61]
https://github.com/komitywa/plantingjs/wiki/planted.json

**Comment by magul** [comment]
@cmwd 
Gdzie jest manifest? Póki co przekazujmy go tak jak jest a później ustalimy, czy nie przekazywać go jakoś inaczej.
Dodatkowo musimy przekazywać index w tabeli plantedobjects, bo nie wiadomo, który to obiekt został wysadzony. Tutaj też możemy przekazywać bardziej wyszukaną informację niż indeks tabeli, ale to też zróbmy w jakimś innym issue, tak by nie zatrzymało nas to przed zmianami w plantingjs.org i w wysadzulice.pl.

**Comment by cmwd** [comment]
@magul 
Wprowadziłem poprawki. Dodałem właściwość `manifest` i `id` dla elementów tablicy `objects`

**Comment by cmwd** [comment]
> Tutaj też możemy przekazywać bardziej wyszukaną informację niż indeks tabeli, ale to też zróbmy w jakimś innym issue, tak by nie zatrzymało nas to przed zmianami w plantingjs.org i w wysadzulice.pl.

założyłem zadanie https://github.com/komitywa/plantingjs.org/issues/34

@magul potwierdź czy wszystko jest ok i czy można zamknąć to zadanie.

**Comment by magul** [comment]
@cmwd I've just reviewed planted.json schema and it looks ok. I'm closing ticket right now,
