### ISSUE TITLE
We need to establish set of rules for linter

### ISSUE THREAD

**Issue by magul** [komitywa/plantingjs#95]
I've already configured ESLint with one rule.

We need to decide, what rules we want to obey.

List of rules: http://eslint.org/docs/rules/

@cmwd @MarekBleschke fill free to suggest anything.

**Comment by cmwd** [comment]
i suggest to use airbnb config.
https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb
https://github.com/airbnb/javascript

**Comment by magul** [comment]
@MarekBleschke do You have any suggestions?

**Comment by magul** [comment]
Ok, we're going with airbnb config.

**Comment by MarekBleschke** [comment]
Looks good, I'm ok with that.

niedz., 25.10.2015 o 17:00 użytkownik Tomasz Magulski <
notifications@github.com> napisał:
